name: Deploy AWS Lambda with CDK

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️ Setup Node.js for CDK
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️ Setup Go for Lambda
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      # 4️ Install AWS CDK
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # 5️ Install Dependencies
      - name: Install Dependencies
        run: |
          cd cdk
          npm install

      # 6️ Configure AWS Credentials (OIDC-based authentication)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125333901:role/githubActionOIDCRole
          aws-region: us-east-1

      # 7️ Build the Go Lambda Function
      # - name: Build Lambda Function
      #   run: |
      #     cd lambda
      #     go mod tidy
      #     GOOS=linux GOARCH=amd64 go build -o main main.go
      #     cd ..

      # 8️ Build and Push Docker Image (ECR)
      # - name: Build and Push Docker Image
      #   run: |
      #     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      #     docker build -t go-lambda ./lambda
      #     docker tag go-lambda:latest YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/go-lambda:latest
      #     docker push YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/go-lambda:latest

      # 9️ bootstrap CDK
      - name: CDK Bootstrap
        run: |
          cd cdk
          cdk bootstrap aws://905418402570/us-east-1

      # 9️ Synthesize CloudFormation template
      - name: CDK Synth
        run: |
          cd cdk
          cdk synth

      # 10 Deploy CDK Stack
      - name: CDK Deploy
        run: |
          cd cdk
          cdk deploy --require-approval never