name: Deploy VPC Stack with CDK

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cdk/lib/vpc-stack.ts'
      - '.github/workflows/deploy-vpc.yml'

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: 905418022647
  GITHUB_ROLE_NAME: GithubActionOIDCRole

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy VPC to AWS
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js for CDK
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install AWS CDK
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Install Dependencies
      - name: Install Dependencies
        working-directory: cdk
        run: npm install

      # Configure AWS Credentials (OIDC-based authentication)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.GITHUB_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      # Determine ENV based on branch
      - name: Set Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENV=dev" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT  # Default to dev
          fi

      # bootstrap CDK
      - name: CDK Bootstrap
        working-directory: cdk
        run: cdk bootstrap aws://${{env.ACCOUNT_ID}}/${{env.AWS_REGION}}

      # Synthesize CloudFormation template
      - name: CDK Synth
        env:
          ENV: ${{ steps.set-env.outputs.ENV }}
        working-directory: cdk
        run: |
          export ENV=$ENV
          cdk synth VpcStack

      # Deploy CDK Stack
      - name: CDK Deploy
        env:
          ENV: ${{ steps.set-env.outputs.ENV }}
        working-directory: cdk
        run: |
          export ENV=$ENV
          cdk deploy VpcStack --require-approval never 