name: Build and Push Docker Image

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # # 2️ Setup Node.js for CDK
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18

      # 3️ Setup Go for Lambda
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      # # 4️ Install AWS CDK
      # - name: Install AWS CDK
      #   run: npm install -g aws-cdk

      # # 5️ Install Dependencies
      # - name: Install Dependencies
      #   run: |
      #     cd cdk
      #     npm install

      # 6️ Configure AWS Credentials (OIDC-based authentication)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125331966:role/githubActionOIDCRole
          aws-region: us-east-1

      # 7️ build and push Docker Image (ECR)
      - name: Build and Push Docker Image
        run: |
          chmod +x scripts/build-and-push.sh
          ./scripts/build-and-push.sh
