name: Populate SSM Parameters

on:
  push:
    branches:
      - main
    paths:
      - 'config/lambda-config.json'  # Trigger on config changes
  workflow_dispatch:  # Allow manual runs

env:
  AWS_REGION: us-east-1  # Change to your region
  ECR_REPOSITORY_PREFIX: lambda  # Prefix for your ECR repositories
  ACCOUNT_ID: 381491935825  # Change to your account ID
  GITHUB_ROLE_NAME: GithubActionOIDCRole  # Change to your role name

permissions:
  id-token: write
  contents: read

jobs:
  populate-ssm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS Credentials (OIDC-based authentication)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.GITHUB_ROLE_NAME }}  # Replace with your role ARN
          aws-region: ${{ env.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Populate SSM Parameters
        run: |
          # Common AWS CLI arguments
          SSM_ARGS="--type String --overwrite --region ${{ env.AWS_REGION }}"

          # Iterate over each Lambda config
          for name in $(jq -r 'keys[]' config/lambda-config.json); do
            config=$(jq -c -r --arg name "$name" '.[$name]' config/lambda-config.json)
            echo "Populating SSM for $name: $config"
            aws ssm put-parameter \
              --name "/lambda/$name/config" \
              --value "$config" \
              $SSM_ARGS
          done

          echo "Successfully populated SSM parameters."